### ISSUE TITLE
Initial implementation

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards_nodejs_app#1]
The initial implementation should have the following properties

* [x] fetch code from colocated notebook file on start
    * [x] configurable path on disk
* [x] use jupyter-js-services and jupyter-js-output-area, not thebe
* ~~ability to filter websocket messages~~ see issue #6
* [x] supports one or more frontend browser client connections at a time and properly 

Other issues will be opened about follow-on features.

**Comment by parente** [comment]
Continuation of https://github.com/jupyter-incubator/dashboards/issues/135

**Comment by dalogsdon** [comment]
The initial implementation can be found in PR #5 

> fetch code from colocated notebook file on start (configurable path on disk)

Currently it will read notebook files placed in the `data` directory in the root of the project. This needs to be updated to read from a configurable path.

> use jupyter-js-services and jupyter-js-output-area, not thebe

Done

> filters all but comm channel messages from the frontend

Not done

> supports one or more frontend browser client connections at a time and properly

Have not done testing on this, but should support multiple connections due to its simplicity. There is no concept of users at the moment, so all notebooks files in the data directory are accessible by anyone.

Do we want to create new issues for the remaining work in these tasks or keep working in this issue until all are complete? I expect each could build up a discussion, especially filtering and multi-user.

**Comment by parente** [comment]
> Do we want to create new issues for the remaining work in these tasks or keep working in this issue until all are complete? I expect each could build up a discussion, especially filtering and multi-user.

If filtering is implementable atop what exists here, that's enough for the moment and we can open a follow-on about comm channel only.

We don't need anything special for authorization for multiple users, just need to make sure the server is non-blocking across users. Authentication is already issue #4.

**Comment by dalogsdon** [comment]
Added config for notebook directory location. We will close this issue and continue work in other issues as discussed in previous comments.

**Comment by parente** [comment]
Feel free to modify the issues too to better fit how you want to chunk up the work.
