### ISSUE TITLE
Get a demo with widgets and plots working

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards_nodejs_app#53]
Go beyond the basic simple / web3. See what happens.

**Comment by parente** [comment]
Some notes for myself for later. I'll write these up in more detail because we're going to need to sync with ipywidgets and jupyter lab plans.

* Use of `require()` in the notebook to create custom widgets
* Use of `IPython/Jupyter.notebook` in the notebook
* Use of `base/js/events` in the notebook
* Emitting JS as display output from a function

**Comment by parente** [comment]
Backed off from scotch demo which is a pretty advanced use of widgets with custom eventing and the like. Here's a simpler dashboard with one static plot and another that should re-render when a new value is picked from the dropdown. The kernel definitely does the re-render, but the plot never updates.

![simple_dash](https://cloud.githubusercontent.com/assets/153745/12798029/31fad728-ca95-11e5-82f2-1fe6da6358b8.png)

**Comment by parente** [comment]
The re-rendered plots are making it back to the browser on the iopub channel as comm messages. But there's nothing in the current dashboard.js code to consume comm channel messages. The output area for the plot was initially created by a execute_request from the notebook code, so it seems reasonable that the dashboard JS is also responsible for handling updates to it, even if it's being driven by widget interaction.

**Comment by parente** [comment]
@jdfreder Need a bit of insight into what we should be doing to handle `display_data` generated from the Python kernel in response to a ipywidgets user action. 

The screenshot two comments up is our simple example. It's derived from the notebook here: https://gist.github.com/parente/93f42341b17b14943bcb

The ipywidget dropdown on the right side is created by an `@interact` function that returns a new matplotlib plot every time the user picks a new value. I can see the base64 encode of the plot image coming back as `display_data` with a parent header type of `comm_msg` to the frontend, but then it gets dropped on the floor.

Who should be handling that `display_data` on the iopub channel with the comm action as the parent? Should the ipywidgets that triggered the change (seems wrong)? Our widget manager impl (maybe what happens in notebook today)? Something else?

Just trying to get my head around what component has what responsibility.

**Comment by jdfreder** [comment]
Hi @parente , this is looking great so far! :tada: 

Regarding message routing, the most important piece is the message callbacks object (dictionary), which is used by the Notebook machinery to handle messages in response to the sent message.  That is defined in the manager base, [here](https://github.com/ipython/ipywidgets/blob/master/jupyter-js-widgets/src/manager-base.js#L106), which then gets passed in as an argument to the comm send method, which eventually makes its way down to kernel.js, its final resting place.  There it waits till a response message is received from the backend.  When a response message is received, the callbacks object is looked up in a dictionary by original header message id (the message id for the message that the current message is a response to).  The kernel then uses the callback object to lookup a callback depending on the type of message, for display data this would point a function of the cell's output area.

You are using jupyter-js-services, right?  The jupyter-js-services in theory should be very similar, but instead of a callbacks object, I believe there's a kernel future object returned as a result of the call, where you specify similar callbacks.  Since the shim abstracts this out, you can continue to work with the API we are using now, the callbacks object.  Your job is to specify the callback for the correct cell there.  If your widget view is in the correct cell, this shouldn't be too difficult (in theory).  It's unfortunate that that's one of the last pieces that needs to be decoupled of the manager base to the notebook, see [here](https://github.com/ipython/ipywidgets/blob/master/jupyter-js-widgets/src/manager-base.js#L111) where the cell is stored in the view's "options" (metadata) object.  When your custom manager displays the view you should store the owner cell's instance in the options object too (see [here](https://github.com/ipython/ipywidgets/blob/master/jupyter-js-widgets/src/manager-base.js#L83)), then in your custom callbacks() method, you can get the correct method of that cell that can handle display data.

It will probably take some effort for this to sink in, I have to re-read it every once and a while (like now) to really wrap my head around it.  If I can help more, please let me know.

**Comment by parente** [comment]
Thanks @jdfreder. I'll need to go through our code and your response a few times to pair things up. One quick clarification:

>  I believe there's a kernel future object returned as a result of the call, where you specify similar callbacks.

Yes, we're using jupyter-js-widgets and are listening to the `future.onIOPub` here:

https://github.com/jupyter-incubator/dashboards_nodejs_app/blob/master/public/js/kernel.js#L84

But this callback only gets invoked for the initial plot render, the one that results from doing the initial `execute_request` that puts the widget in the cell along with the initial plot `display_data`. After that, picking new items from the dropdown don't trigger any more callbacks on that future. 

This is where I'm guessing we need to be doing more than we are currently, like storing the `cell` (whatever that means over here) when we create a view.

I'll dig in with @jhpedemonte and see where we wind up.

**Comment by jdfreder** [comment]
Awesome, yeah, you should be able to stick close to implementing in a similar way too the widget machinery for the notebook because the shim abstracts that out, see [here](https://github.com/ipython/ipywidgets/blob/master/jupyter-js-widgets/src/services-shim.js#L203).  IOW in the code you implement you shouldn't be dealing with kernel futures but instead you'll be using the callback style API.

**Comment by parente** [comment]
@jdfreder We paired on this and are still stuck on how to proceed. It might be we're ahead of where the widgets are and trying to do something that's not possible yet. If you've got some time to sit with us in appear, that would help. We can ping in gitter and find a common time.

**Comment by jdfreder** [comment]
Sure, does the code exist in a branch of `dashboards_nodejs_app` or on one of your personal repos so I can take a look?

**Comment by parente** [comment]
@jdfreder Right after I posted that msg, we had a late afternoon mental breakthrough on your hints about how to link our jupyter-js-output-areas to widgets within them in order to handle `display_data` messages. I think we're good for the moment. Thanks!

**Comment by jdfreder** [comment]
Sweet!  Glad I was able to help.  When you've got the code up in a public place can you ping me?  I'd like to study it -  it's a goal of mine to improve all of this and some concrete use cases would be tremendously helpful.  Sorry for the bleeding edge pain!

**Comment by parente** [comment]
@jdfreder PR #60 is now cleaned up with code that makes this really simple dropdown + matplotlib dashboard notebook work (https://gist.github.com/parente/93f42341b17b14943bcb). It'll need to change when ipython/ipywidgets#353 gets merged in one form or another.

I'll try a slightly more complex notebook next.

The comments I threw into our widget manager might make more sense in the base as documentation of the API. Let me know if that makes sense to contribute or not.

**Comment by parente** [comment]
Example of what works so far:

![jupyter_dashboards](https://cloud.githubusercontent.com/assets/153745/12896303/454df8ea-ce6f-11e5-9ae3-1fb673999166.gif)

**Comment by jdfreder** [comment]
Wow, this is awesome!  Great work @parente !!
